# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=60)),
                ('segundo_nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('primer_apellido', models.CharField(max_length=60)),
                ('segundo_apellido', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo_documento_identidad', models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Tarjeta de Identidad', 'Tarjeta de Identidad')], max_length=100)),
                ('numero_documento', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=100)),
                ('genero', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=60, null=True)),
                ('pais_procedencia', models.CharField(blank=True, choices=[('Colombia', 'Colombia'), ('Brazil', 'Brazil'), ('Argentina', 'Argentina'), ('Chile', 'Chile')], max_length=100, null=True)),
                ('departamento_procedencia', models.CharField(blank=True, choices=[('Cauca', 'Cauca'), ('Valle del Cauca', 'Valle del Cauca'), ('Antioquia', 'Antioquia'), ('Nariño', 'Nariño')], max_length=100, null=True)),
                ('municipio_procedencia', models.CharField(blank=True, choices=[('Florida', 'Florida'), ('Cali', 'Cali'), ('Buga', 'Buga'), ('Medellín', 'Medellín')], max_length=100, null=True)),
                ('zona_ubicacion', models.CharField(blank=True, choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Oriente', 'Oriente'), ('Occidente', 'Occidnete')], max_length=100, null=True)),
                ('barrio', models.CharField(blank=True, max_length=60)),
                ('direccion', models.CharField(blank=True, max_length=60)),
                ('estrato', models.CharField(blank=True, max_length=20)),
                ('comuna', models.CharField(blank=True, max_length=60)),
                ('vereda', models.CharField(blank=True, max_length=60)),
                ('corregimiento', models.CharField(blank=True, max_length=60)),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Union Libre', 'Union Libre')], max_length=100, null=True)),
                ('numero_hijos', models.CharField(blank=True, max_length=20)),
                ('cabeza_jefe_familia', models.CharField(blank=True, choices=[('Jefe', 'Jefe'), ('Cabeza', 'Cabeza')], max_length=100, null=True)),
                ('ocupacion', models.CharField(blank=True, choices=[('Estudiante', 'Estudiante'), ('Independiente', 'Independiente'), ('Asalariado', 'Asalariado')], max_length=100, null=True)),
                ('nivel_escolaridad', models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universitaria', 'Universitaria')], max_length=100, null=True)),
                ('estudios_completos', models.BooleanField()),
                ('educacion_desarrollo_humano', models.CharField(blank=True, choices=[('Educaccion para el Trabajo', 'Educaccion para el Trabajo'), ('Desarrollo Humano', 'Desarrollo Humano')], max_length=100, null=True)),
                ('etnia', models.CharField(blank=True, choices=[('Afro', 'Afro'), ('Mestizo', 'Mestizo'), ('Indígena', 'Indígena')], max_length=100, null=True)),
                ('comunidad_indigena', models.CharField(blank=True, max_length=60, null=True)),
                ('grupo', models.CharField(blank=True, choices=[('Poblacionales', 'Poblacionales'), ('Comunitarios', 'Comunitarios'), ('Sociales', 'Sociales')], max_length=100, null=True)),
                ('posee_discapacidad', models.BooleanField()),
                ('cual_discapasidad', models.CharField(blank=True, choices=[('Auditiva', 'Auditiva'), ('Visual', 'Visual'), ('Cognitiva', 'Cognitiva')], max_length=100, null=True)),
            ],
        ),
    ]
