# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitanteCalle', '0002_auto_20180220_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grupo_poblacional',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cuál?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cabeza_jefe_familia',
            field=models.CharField(blank=True, choices=[('Jefe', 'Jefe'), ('Cabeza', 'Cabeza')], max_length=100, null=True, verbose_name='Es cabeza de familia o jefe(a) de hogar'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comunidad_indigena',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Si su respuesta es indígena indique a qué comunidad pertenece'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cual_discapasidad',
            field=models.CharField(blank=True, choices=[('Auditiva', 'Auditiva'), ('Visual', 'Visual'), ('Cognitiva', 'Cognitiva')], max_length=100, null=True, verbose_name='Cuál?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='educacion_desarrollo_humano',
            field=models.CharField(blank=True, choices=[('Educaccion para el Trabajo', 'Educaccion para el Trabajo'), ('Desarrollo Humano', 'Desarrollo Humano')], max_length=100, null=True, verbose_name='Ha llevado a cabo alguno de estos estudios de Educación para el Trabajo y el Desarrollo Humano'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estudios_completos',
            field=models.BooleanField(verbose_name='Realizó sus estudios de manera completa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='etnia',
            field=models.CharField(blank=True, choices=[('Afro', 'Afro'), ('Mestizo', 'Mestizo'), ('Indígena', 'Indígena')], max_length=100, null=True, verbose_name='Autoreconocimiento étnico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo',
            field=models.CharField(blank=True, choices=[('Poblacionales', 'Poblacionales'), ('Comunitarios', 'Comunitarios'), ('Sociales', 'Sociales')], max_length=100, null=True, verbose_name='Pertenece actualmente a alguno de estos grupos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='posee_discapacidad',
            field=models.BooleanField(verbose_name='Posee alguna discapacidad'),
        ),
    ]
