# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitanteCalle', '0003_auto_20180220_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comunidad_indigena',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Si su respuesta es indiigena indique a quee comunidad pertenece'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cual_discapasidad',
            field=models.CharField(blank=True, choices=[('Auditiva', 'Auditiva'), ('Visual', 'Visual'), ('Cognitiva', 'Cognitiva'), ('Fisica', 'Fisica')], max_length=100, null=True, verbose_name='Cual?'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='educacion_desarrollo_humano',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estudios_completos',
            field=models.BooleanField(verbose_name='Realizo sus estudios de manera completa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='etnia',
            field=models.CharField(blank=True, choices=[('Afro', 'Afro'), ('Mestizo', 'Mestizo'), ('Indigena', 'Indigena')], max_length=100, null=True, verbose_name='Autoreconocimiento etnico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo_poblacional',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cual?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ocupacion',
            field=models.CharField(blank=True, choices=[('Estudiante', 'Estudiante'), ('Independiente', 'Independiente'), ('Asalariado', 'Asalariado'), ('Estudiante y Asalariado', 'Estudiante y Asalariado')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento_identidad',
            field=models.CharField(choices=[('Cedula de Ciudadania', 'Cedula de Ciudadania'), ('Cedula de Extranjeria', 'Cedula de Extranjeria'), ('Tarjeta de Identidad', 'Tarjeta de Identidad')], max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='educacion_desarrollo_humano',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, to='HabitanteCalle.Estudios', verbose_name='Ha llevado a cabo alguno de estos estudios de Educacion para el Trabajo y el Desarrollo Humano'),
        ),
    ]
