# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitanteCalle', '0004_auto_20180221_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='educacion_desarrollo_humano',
            field=models.ManyToManyField(blank=True, max_length=100, to='HabitanteCalle.Estudios', verbose_name='Ha llevado a cabo alguno de estos estudios de Educacion para el Trabajo y el Desarrollo Humano'),
        ),
    ]
